In [2]:
import numpy as np

Creation of numpy arrays from list

1D Array

In [3]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [4]:
type(array_from_list)

numpy.ndarray

In [5]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


In [6]:
array_from_list.ndim

1

In [7]:
array_from_list.shape

(5,)

2D Array

In [8]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
type(array_2d)

numpy.ndarray

In [10]:
array_2d.ndim

2

In [11]:
array_2d.shape

(3, 3)

3D Array

In [12]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6],
                     [7, 8]]])

In [13]:
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
type(array_3d)

numpy.ndarray

In [15]:
array_3d.ndim

3

In [16]:
array_3d.shape

(2, 2, 2)

In [17]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6],
                     [7, 8]],

                    [[9, 10],
                     [11, 12]]])

In [18]:
array_3d.shape

(3, 2, 2)

In [19]:
array_3d = np.array([[[1, 2, 3],
                      [3, 4, 5]],

                     [[5, 6, 7],
                     [7, 8, 9]],

                    [[9, 10, 11],
                     [11, 12, 13]]])

In [20]:
array_3d.shape

(3, 2, 3)

In [22]:
array_3d.dtype

dtype('int64')

Inhomogeneous shape of the internal submatrix

In [21]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6, 7],
                     [7, 8, 9]],

                    [[9, 10, 11],
                     [11, 12, 13]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

In [25]:
array_ = np.array([5,-7.4,7.2])
print(array_) ## it will convert all the values to string because homogeneous value stored

[ 5.  -7.4  7.2]


In [26]:
print(array_.dtype)

float64


Item size returns the size in bytes of each element in the array

In [ ]:
print("Item Size of array_ : ", array_.itemsize, "Bytes")

Item Size of array_ :  8 Bytes


data provides a direct buffer to the memory location where the array's data is actually stored

In [28]:
print("data buffer ",array_.data)

data buffer  <memory at 0x1058aae00>


indexing and slicing in numpy

In [29]:
array_from_list

array([1, 2, 3, 4, 5])

In [30]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array_3d

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [11, 12, 13]]])

In [32]:
print(array_from_list[2])

3


In [35]:
print(array_2d[2][2])

9


In [36]:
print(array_3d[1][1][1])

8


In [37]:
print(array_3d[2][1][2])

13


In [40]:
print(array_3d[0][1][0])

3


In [42]:
array_from_list[1:4]

array([2, 3, 4])

In [47]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
array_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [44]:
array_3d

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [11, 12, 13]]])

In [46]:
array_3d[0:2,1,1:]

array([[4, 5],
       [8, 9]])

### Methods in numpy